### ISSUE TITLE
Question about the plugin

### ISSUE THREAD

**Issue by Toast707** [holisticnetworking/title-to-tags#1]
Hi, does this plugin work with posts that are automatically published, like from an rss feed?

**Comment by holisticnetworking** [comment]
You'd have to try it out and see. The plugin works from the save_post action hook, so I believe that it should.

**Comment by holisticnetworking** [comment]
PS: please report back your findings and I'll add them to my FAQs!

**Comment by Toast707** [comment]
Will do.

**Comment by Toast707** [comment]
@holisticnetworking So it looks like tags are being added when automatically posting (rss plugin), but it looks like the tags aren't being attributed to any of the posts—tags are generated, but not applied. Just wanted to let you know, and if you had any ideas how I might be able to get this to work.

**Comment by holisticnetworking** [comment]
Thank you. I'm opening a new issue for this.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=tbelknap@holisticnetworking.net&idSignature=22>

Thomas J Belknap
Senior Web Developer
585.305.1619
http://holisticnetworking.net
